version: '3.8'

services:
  postgres:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: my-postgres-container
    env_file:
      - ./DB/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql # Chemin relatif au dossier contenant le docker-compose.yml
    networks:
      - my_network



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend-container
    working_dir: /app
    command: npm start
    env_file:
      - ./backend/.env.production
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend-container
    env_file:
      - ./frontend/.env
    ports:
      - "443:443"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
