-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.role
(
    id serial NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    id serial NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.token
(
    token_id serial NOT NULL,
    matricule character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_to timestamp without time zone,
    CONSTRAINT token_pkey PRIMARY KEY (token_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    matricule character varying(8) COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    salt character varying COLLATE pg_catalog."default" NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    activation_expiration timestamp with time zone NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (matricule)
);

CREATE TABLE IF NOT EXISTS public.user_data
(
    matricule character varying COLLATE pg_catalog."default" NOT NULL,
    nom character varying COLLATE pg_catalog."default" ,
    prenom character varying COLLATE pg_catalog."default" ,
    adresse character varying COLLATE pg_catalog."default",
    CONSTRAINT user_data_pkey PRIMARY KEY (matricule)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    matricule character varying COLLATE pg_catalog."default" NOT NULL,
    id_role integer NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (matricule, id_role)
);

CREATE TABLE IF NOT EXISTS public.user_status
(
    matricule character varying COLLATE pg_catalog."default" NOT NULL,
    id_status integer NOT NULL,
    CONSTRAINT user_status_pkey PRIMARY KEY (matricule, id_status)
);

ALTER TABLE IF EXISTS public.token
    ADD CONSTRAINT token_matricule_fkey FOREIGN KEY (matricule)
    REFERENCES public."user" (matricule) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_data
    ADD CONSTRAINT "user" FOREIGN KEY (matricule)
    REFERENCES public."user" (matricule) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS user_data_pkey
    ON public.user_data(matricule);


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT data_role FOREIGN KEY (matricule)
    REFERENCES public.user_data (matricule) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT role FOREIGN KEY (id_role)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_status
    ADD CONSTRAINT status FOREIGN KEY (id_status)
    REFERENCES public.status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_status
    ADD CONSTRAINT user_status FOREIGN KEY (matricule)
    REFERENCES public.user_data (matricule) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;